[WIP] tests for abstract densities
bat/BAT.jl pull request #186
Opened 2020-09-02 00:02 UTC by sthayashi

2020-09-02 06:02 UTC, oschulz commented
If you're done with this, can you remove `[WIP]` from the title of the PR?

2020-09-02 16:01 UTC, sthayashi commented
I will be writing more tests for this, unless it's more desirable to write tests for something else. 

https://github.com/bat/BAT.jl/pull/184 should be ready for review

2020-09-02 16:56 UTC, oschulz commented
Sure, that's perfectly fine!

2020-09-12 11:41 UTC, sthayashi commented
It seems the function `map_const_shapes(f::Function, shape::ConstValueShape)` is only used for statistics of a `DensitySampleVector`. Should this be tested in `test_abstract_density.jl`, or is it more appropriate with the other `density_sample.jl` tests?

2020-09-12 13:37 UTC, oschulz commented
`map_const_shapes` will move into ValueShapes, doesn't need a test in BAT

2020-10-02 12:40 UTC, sthayashi commented
Does it make sense that this works?

```
nt_dist = NamedTupleDist(a=Normal())
logpdf(nt_dist, [0])
logpdf(nt_dist, [0, 1])
logpdf(nt_dist, rand(1000))
```
It looks like it takes the first element to evaluate, i.e. `logpdf(Normal(), 0)` for all of them. Just ran into this as I was trying to test `_density_eval_error` on line 163, and am wondering if it should also throw an error when the the number of elements doesn't match the `AbstractDensity` when using `logvalof(density::AbstractDensity, v::Any)`

2020-10-02 15:54 UTC, oschulz commented
> Does it make sense that this works

That should indeed result in an error.

2020-10-08 11:29 UTC, sthayashi commented
Just need to write one more test for 

https://github.com/bat/BAT.jl/blob/a934f6845111aba431e444fd11be32676ff5543c/src/densities/abstract_density.jl#L195

I think this is just used for making the raised error text more readable? Is it good enough to do something simple like

`@test_throws ErrorException logvalgradof(some_dist::AbstractDensity, v::Vector)`.

I don't think there is a way to more directly test this?

The relevant chain of code which ends up calling this is
https://github.com/bat/BAT.jl/blob/a934f6845111aba431e444fd11be32676ff5543c/src/densities/abstract_density.jl#L163-L177
and
https://github.com/bat/BAT.jl/blob/a934f6845111aba431e444fd11be32676ff5543c/src/densities/abstract_density.jl#L197-L203

2020-10-08 11:33 UTC, oschulz commented
Ignore `_strip_duals` for now, that may change in the future.

2020-10-08 11:37 UTC, sthayashi commented
Will check build with updated master, then ready for review.

2020-10-08 11:42 UTC, oschulz commented
Thanks, let me know if it works!

2020-10-08 12:26 UTC, sthayashi commented
Should I change `logvalof` and all related functions in these tests to `BAT.logvalof`, or use the new functions, e.g. `BAT.eval_logval`?

2020-10-08 12:28 UTC, sthayashi commented
I just saw that `BAT.logvalof_unchecked` was completely removed, so I guess use the `BAT.eval_...` versions?

2020-10-08 12:31 UTC, oschulz commented
Yes, `BAT.logvalof_unchecked` is now called `BAT.eval_logval_unchecked`.

2020-10-08 13:20 UTC, sthayashi commented
Ready for review

2020-10-08 13:25 UTC, sthayashi commented
Just saw the typo in the commit message. Should be `test_abstract_density.jl`.

2020-10-08 13:55 UTC, oschulz requested changes

2020-10-08 14:05 UTC, sthayashi commented on test/densities/test_abstract_density.jl
>          @test rand(MersenneTwister(7002), sampler(td)) ≈ [-2.415270938, 0.7070171342, 1.0224848653]
I didn't actually put that in there. I could add similar tests for the other test structs used if it's good to have.

2020-10-08 15:06 UTC, oschulz commented on test/densities/test_abstract_density.jl
>          @test rand(MersenneTwister(7002), sampler(td)) ≈ [-2.415270938, 0.7070171342, 1.0224848653]
Yes, I didn't know about that issue back then (and StableRNG didn't exist yet). We should get rid of similar instances in the tests, but that can be a separate PR. Thanks, I'll merge this one now.

2020-10-23 00:37 UTC, oschulz commented
Could you rebase this on the current master and update as necessary?

2020-10-28 19:41 UTC, sthayashi commented
Tasks before ready for review
- [ ]  Clean commit history

2020-11-02 13:13 UTC, oschulz commented
Thanks!

2020-11-02 13:14 UTC, merged