Allow keywords when running UltraNest ?
bat/BAT.jl pull request #253
Opened 2021-02-05 20:06 UTC by Cornelius-G

Or is there a reason why these keywords were disabled?
Also, I'm not sure about `viz_callback` in lines 65 and 139

2021-02-05 22:10 UTC, oschulz commented
> Or is there a reason why these keywords were disabled?

Oooops, thanks! Must have happened while debugging of the initial implementation ...

2021-02-05 22:19 UTC, oschulz requested changes

2021-02-05 22:19 UTC, oschulz commented on src/samplers/nested_sampling/ultranest.jl
> +    paramnames = all_active_names(varshape(density_notrafo))
UltraNest only sees the transformed parameter space, so for this to work, `all_active_names` needs to support things like `BAT.all_active_names(ArrayShape{Real}(5))` too. If `all_active_names` gets support for `ScalarShape` and `ArrayShape` (can be done in this PR), that would work.

However, "valueshapes_utils.jl" will need to move from "plots" to "utils", to have a sane order of src includes.

2021-02-05 22:49 UTC, Cornelius-G commented on src/samplers/nested_sampling/ultranest.jl
> +    paramnames = all_active_names(varshape(density_notrafo))
But  `ScalarShape` and `ArrayShape` don't contain any information on the names, right? 
`all_active_names` works by just accessing the keys of a `NamedTupleShape` (usually coming from the posterior or prior).
For my tests, the code above worked, but I guess because I'm testing on a posterior where the prior has names assigned to the parameters. But the CI tests use a prior that has no names. 
So maybe we can just do something like 
```julia
if isa(varshape(density_notrafo), NamedTupleDist)
paramnames = all_active_names(varshape(density_notrafo))
end
```
?

2021-02-06 01:35 UTC, oschulz commented on src/samplers/nested_sampling/ultranest.jl
> +    paramnames = all_active_names(varshape(density_notrafo))
> But ScalarShape and ArrayShape don't contain any information on the names, right?

2021-02-06 01:37 UTC, oschulz commented on src/samplers/nested_sampling/ultranest.jl
> +    paramnames = all_active_names(varshape(density_notrafo))
> But ScalarShape and ArrayShape don't contain any information on the names, right?

Yes, but it can just return `"v"` for `ScalarShape` and something like `["v_$i" for i in 1:ndims]` for `ArrayShape`.

2021-02-06 15:04 UTC, Cornelius-G commented on src/samplers/nested_sampling/ultranest.jl
> +    paramnames = all_active_names(varshape(density_notrafo))
Yes sure, with generic names that is possible. 
Ah, I see why I had "valueshapes_utils.jl" in "plotting" and not in "utils". It needs to know some of the BAT types.
Any suggestions where to place it/how to include it?

2021-02-06 20:39 UTC, oschulz commented on src/samplers/nested_sampling/ultranest.jl
> +    paramnames = all_active_names(varshape(density_notrafo))
Let's split it - the BAT-independent part can go in "utils/", in preparation for moving it into ValuesShapes eventually. The BAT-dependent part can stay in plots or maybe even move closer to the types it depends on.

2021-02-09 11:46 UTC, oschulz requested changes

2021-02-09 11:46 UTC, oschulz commented on examples/benchmarks/benchmark_results/results/results_2D.tex
> +\begin{table}
This should not be committed.

2021-02-09 11:46 UTC, oschulz commented on examples/benchmarks/benchmark_results/results/results_2D.txt
> +┌─────────────────┬──────────────────┬────────────────────┬──────────────────┐
This should not be committed.

2021-02-09 11:46 UTC, oschulz commented on examples/benchmarks/benchmark_results/results/run_stats_2D.tex
> +\begin{table}
This should not be committed.

2021-02-09 11:46 UTC, oschulz commented on examples/benchmarks/benchmark_results/results/run_stats_2D.txt
> +┌──────────────┬────────┬─────────┬───────┐
This should not be committed.

2021-02-09 12:18 UTC, Cornelius-G commented on examples/benchmarks/benchmark_results/results/run_stats_2D.txt
> +┌──────────────┬────────┬─────────┬───────┐
Oops, right. Didn't notice these files.

2021-02-09 12:57 UTC, oschulz commented on examples/benchmarks/benchmark_results/results/run_stats_2D.txt
> +┌──────────────┬────────┬─────────┬───────┐
Kinda suspected they snuck in there. :-)

2021-02-09 12:58 UTC, merged

2021-02-09 12:58 UTC, oschulz commented
Thanks!