[WIP] Adding nested sampling with NestedSamplers.jl
bat/BAT.jl pull request #287
Opened 2021-05-27 10:12 UTC by WillyHK

2021-05-27 10:56 UTC, oschulz commented
Nice going, guys!

2021-05-28 07:47 UTC, Cornelius-G commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +    struct TuringNestedSamplers <: AbstractUltraNestAlgorithm
I guess the `AbstractUltraNestAlgorithm` here is a copy paste error :wink:

2021-05-28 07:50 UTC, Cornelius-G commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +    "Number of live-points."
Also, I don't think you can just put those stings in here. What you had before was ok, I guess.

2021-06-02 11:43 UTC, oschulz requested changes

2021-06-02 11:43 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/tns_proposals.jl
> +export TNS_Uniformly
Let's not export these until they are documented properly.

2021-06-02 11:43 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +############################################################################################################
BAT.jl doesn't use "headline" comments like this.

2021-06-02 11:43 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +end
File should end with a newline.

2021-06-02 11:43 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +    function tns_posterior(x)
Use `tns_posterior = logdensityof(density)` instead.

2021-06-02 11:43 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +    model = NestedModel(tns_posterior, tns_prior_trafo);
Just pass `identity` as `tns_prior_trafo`.

2021-06-02 11:43 UTC, oschulz commented on src/BAT.jl
> +        @require MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d" include("samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl") # loads if both packages there
Do we need to require `MCMCChains` (do we uses types of functions in it explicitly)?

2021-06-02 11:43 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +        result = samples_notrafo, result_trafo = samples_trafo, trafo = trafo,
Should return the integral estimate as well, it's one of the main advantages of nested sampling, after all.

2021-06-02 11:44 UTC, oschulz commented
Nice! I added a review with a few comments. And there should be some tests, at least, before we merge it. :-)

2021-06-19 11:54 UTC, oschulz commented
Regarding ESS estimation, this may be of interest, it's fairly recent: https://arxiv.org/abs/1602.03572

2021-07-02 16:45 UTC, WillyHK commented
I took another quick look and everything seems to work, have run the tests several times and there was no problem.

I think the code should be possible to merge

2021-07-03 11:58 UTC, oschulz commented
There's a merge conflict regarding your additions to "Project.toml" - test dependencies are now in "test/Project.toml", not in the main "Project.toml" anymore. Could you change the PR accordingly?

2021-07-03 13:03 UTC, WillyHK commented
Oh, sry for that, hopefully it's fine now @oschulz

2021-07-04 10:02 UTC, oschulz requested changes

2021-07-04 10:02 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +    struct TuringNestedSamplers <: AbstractSamplingAlgorithm
Let's rename this to `EllipsoidalNestedSampling`

2021-07-04 10:02 UTC, oschulz commented on test/samplers/nested_sampling/test_turing_nestedSamplers.jl
> +@testset "test_turing_nestedSamplers" begin
Should be `@testset "ellipsoidal_nested_sampling"`

2021-07-04 10:02 UTC, oschulz commented on test/samplers/nested_sampling/test_turing_nestedSamplers.jl
> +# This file is a part of BAT.jl, licensed under the MIT License (MIT).
Let's name this file "test_ellipsoidal_nested_sampling.jl"

2021-07-04 10:02 UTC, oschulz commented on src/samplers/nested_sampling/turing_nestedSamplers/turing_nestedSamplers.jl
> +using .NestedSamplers               # used in this file, because this file ist only load if it is required
Let's name this file "ellipsoidal_nested_sampling.jl"

2021-07-04 20:25 UTC, oschulz requested changes

2021-07-04 20:25 UTC, oschulz commented on src/samplers/nested_sampling/ellipsoidal_nested_sampling/ens_bounds.jl
> +abstract type ENS_Bound end
Type names should not contain underscores, just use `ENSBounds` and so on.

2021-07-04 20:25 UTC, oschulz commented on src/samplers/nested_sampling/ellipsoidal_nested_sampling/ens_bounds.jl
> +export ENS_NoBounds
Let's not export these for now. So no `export`, and use `struct BAT.ENSNoBounds` in the docstring. Also all docstrings should contain `*Experimental feature, not part of stable public API.*` for now.

2021-07-04 20:25 UTC, oschulz commented on src/samplers/nested_sampling/ellipsoidal_nested_sampling/ens_proposals.jl
> +
For `@with_kw` structs, add the fields to the docstring by including

```julia
Constructors:

* ```$(FUNCTIONNAME)(; fields...)```

Fields:

$(TYPEDFIELDS)
```

See ultranest.jl, etc.

2021-07-04 20:25 UTC, oschulz commented on src/samplers/nested_sampling/ellipsoidal_nested_sampling/ens_proposals.jl
> +    ratio::Float64 = 0.5
Maybe document the semantics of the fields (see ultranest.jl for examples).

2021-07-05 19:21 UTC, oschulz approved these changes

2021-07-05 20:25 UTC, oschulz commented
Looks good to merge, as soon as the test failures are gone.

2021-07-06 08:03 UTC, WillyHK commented
I have found an error message in the full log, which seems to be the reason for the fail:

 "Warning: Error requiring` NestedSamplers` from `BAT`"
 "UndefVarError: EllipsoidalNestedSampling not defined"

I have now checked the code again, but actually found no reason for it.

Could the problem maybe be that the tests are running in an environment (on a Gitserver?), where NestedSamplers.jl was not added? 
(I think that would be necessary for the @require statement so that the code is loaded)

Please apologize if this is a wrong thought, may you have another idea why the error occurs @oschulz

2021-07-06 15:41 UTC, oschulz commented
We still have this `invalid keyword argument syntax "prop.ratio"` error on Julia v1.3 x64 - any idea why?

2021-07-06 20:27 UTC, WillyHK commented
Not really.
The only codeline, where prop.ratio is used, is in the return function for ENSRandomWalk in ens_proposals, but there it looks fine to me.

2021-07-07 09:19 UTC, oschulz commented
I'll re-run the tests to see if it's a sporadic failure.

2021-07-07 12:03 UTC, oschulz commented
Nope, seems to always fail on Julia 1.3 ubuntu x64. We should figure this out before we merge.

2021-07-07 12:04 UTC, oschulz commented
@WillyHK could you try running the tests locally (`Pkg.test("BAT")`), on a 64-bit Linux system with Julia 1.3 ?

2021-07-07 13:34 UTC, WillyHK commented
With julia 1.6 it runs first try, locally at Ubuntu x64, I will later download version 1.3 and test it again

2021-07-07 15:49 UTC, WillyHK commented
Update: with julia version 1.3 the known error `invalid keyword argument syntax "prop.ratio"` occured locally too, on the same system it worked with julia 1.6. So it seems to be a problem with the old julia version

2021-07-07 17:15 UTC, WillyHK commented
Update: I try a few more tries with different versions of julia, the result is:

With julia 1.3 or 1.4 the test fails with the error in the upper comment
With julia 1.5 or 1.6 all tests are succesfull

2021-07-07 17:56 UTC, oschulz commented
> With julia 1.3 or 1.4 the test fails with the error in the upper comment

If that happens locally too, can you and @Cornelius-G try to figure out why it happens?

2021-07-07 19:24 UTC, WillyHK commented
So, now locally all test passed succesfully for julia 1.3

Thank you for giving me the hint, that the julia version could be the reason for the testfail @oschulz 

the problem was that julia changed the handling of different syntaxes for optional keywords over the versions, which i didn't know.

2021-07-07 20:21 UTC, oschulz commented
> Julia changed the handling of different syntaxes for optional keywords over the versions

Oh, that's where it was - of course, sorry, I should have seen that. Ok, let's see if tests pass now. :-)

2021-07-08 05:47 UTC, merged

2021-07-08 05:47 UTC, oschulz commented
Thanks!!