[WIP] Fix problems due to new Trajectory type in AdvancedHMC.jl
bat/BAT.jl pull request #309
Opened 2021-07-29 23:09 UTC by sthayashi

2021-07-29 23:12 UTC, sthayashi commented
`BAT` currently only implements the NUTS sampler from `AdvancedHMC.jl`. Thus the previous commit https://github.com/bat/BAT.jl/commit/bb00ab4357535a21e37a4df00ce32a1f7722a1a7 only made the necessary changes to allow the use of NUTS to resume. This PR brings `BAT` back to the previous problem with non-NUTS samplers, namely it assumes there is a tree depth, which a static trajectory does not have.

2021-07-30 21:46 UTC, oschulz requested changes

2021-07-30 21:46 UTC, oschulz commented on src/samplers/mcmc/ahmc/ahmc_sampler.jl
> +function AdvancedHMC.transition(rng::AbstractRNG, hamiltonian::AdvancedHMC.Hamiltonian, proposal::AdvancedHMC.Trajectory, z::AdvancedHMC.PhasePoint)
Can we do this differently? This is type piracy ...

2021-08-02 21:56 UTC, sthayashi commented
Closing this PR. Master branch should already have the `ERROR: type NamedTuple has no field tree_depth` when using `BAT.FixedStepNumber` or `FixedTrajectoryLength` proposal.

2021-08-02 21:56 UTC, closed without merging