WIP MCMC with transforms Interface
bat/BAT.jl pull request #409
Opened 2023-06-30 12:20 UTC by waldie11

FYI
@oschulz @Cornelius-G

2023-06-30 20:06 UTC, oschulz commented
Can you check the

```
Base.Meta.ParseError("parsing error in src/samplers/transformed_mcmc/struct_list.jl:34: missing comma or } in argument list")
```

CI error on Julia 1?

2023-06-30 20:28 UTC, oschulz requested changes

2023-06-30 20:28 UTC, oschulz commented on src/samplers/transformed_mcmc/example.jl
> +using BAT
Examples should live in "examples", not in "src" :-)

2023-06-30 20:28 UTC, oschulz commented on src/samplers/transformed_mcmc/mcmc_algorithm.jl
> +@with_kw struct TransformedMCMCIteratorInfo
Stuff like this we don't need to duplicate.

2023-06-30 20:28 UTC, oschulz commented on src/samplers/transformed_mcmc/mcmc_algorithm.jl
> +    abstract type TransformedMCMCInitAlgorithm
We don't need to duplicate abstract types like these, I think.

2023-07-06 08:11 UTC, oschulz commented
I've updated this to use the new BATContext. "transformed_example.jl" doesn't fully run through, but I'm not sure if that's related.

2023-07-06 08:37 UTC, oschulz commented
`TransformedAdaptiveMHTuning` in the example works now, but

```
r_hmc = @time BAT.bat_sample_impl(posterior, MCMCSampling(mcalg=HamiltonianMC(), nchains=4, nsteps=4*20000), context)
```

in the example doesn't work yet, but that's to be expected currently, right?

I think `BATContext`-wise this is fine now.

2023-07-06 08:41 UTC, Cornelius-G commented
> `TransformedAdaptiveMHTuning` in the example works now, but
> 
> ```
> r_hmc = @time BAT.bat_sample_impl(posterior, MCMCSampling(mcalg=HamiltonianMC(), nchains=4, nsteps=4*20000), context)
> ```
> 
> in the example doesn't work yet, but that's to be expected currently, right?

Hm, for me this line works. As it should, because that is just the "good old" HMC smapling, not using the new transformations.

2023-07-06 09:02 UTC, oschulz commented
Ah - well, in any case, I think the adaption to BATContext is complete.

2023-07-06 09:13 UTC, Cornelius-G commented on src/samplers/transformed_mcmc/mcmc_tuning/mcmc_proposalcov_tuner.jl
> +function tuning_update!(tuner::TransformedProposalCovTuner, chain::TransformedMCMCIterator, samples::DensitySampleVector)
I guess we need to revert this change, because the CI tests fail due to this line.
`TransformedMCMCIterator` is a subtype of `MCMCIterator`. Dispatch should be fine just using the `tuner` argument.

2023-07-06 12:14 UTC, oschulz commented on src/samplers/transformed_mcmc/mcmc_tuning/mcmc_proposalcov_tuner.jl
> +function tuning_update!(tuner::TransformedProposalCovTuner, chain::TransformedMCMCIterator, samples::DensitySampleVector)
Sure, we can revert it. But why does it cause errors? For a `TransformedProposalCovTuner` the chain must be a `TransformedMCMCIterator`, right?

2024-05-21 13:27 UTC, oschulz commented
@Micki-D needs to be updated to API changes.

2024-06-05 13:50 UTC, oschulz commented
Closing in favor of #441

2024-06-05 13:50 UTC, closed without merging