Allow to pass Optim.Options to bat_findmode
bat/BAT.jl pull request #423
Opened 2023-09-04 15:51 UTC by Cornelius-G

Allows to pass all the [Optim.Options](http://julianlsolvers.github.io/Optim.jl/v0.9.3/user/config/#general-options) to `bat_findmode`.

Example:
```
using BAT
using Optim

posterior = BAT.example_posterior()

optalg = OptimAlg(;optalg = Optim.NelderMead(), options=Optim.Options(iterations=200))

bat_findmode(posterior, optalg)
```

2023-09-04 15:59 UTC, Cornelius-G commented
Ah, I just realize this solution might be a problem since we declared `OptimAlg` part of the stable API 😖
Any ideas how to handle this?

2023-09-05 07:08 UTC, oschulz requested changes

2023-09-05 07:08 UTC, oschulz commented on src/extdefs/optim_defs.jl
> +    options::OPTS = ext_default(pkgext(Val(:Optim)), Val(:DEFAULT_OPTS))
How about `algopts` instead of just `options`, to be a bit more specific?

2023-09-05 07:16 UTC, Cornelius-G commented
> Which options would the user set, typically (since BAT will also set some, we need to ensure they don't clash)?

I was mostly thinking about things like: `Iterations` and the values for determining convergence, like `x_tol`, `f_tol` etc.

2023-09-05 07:33 UTC, oschulz commented
> I was mostly thinking about things like: Iterations and the values for determining convergence, like x_tol, f_tol etc.

Hm, since those are pretty fundamental, maybe we should offer (some of those) as explicit fields of `OptimAlg` directly, so the user can use them across optimization backends in a consistent fashion?

2023-09-05 08:27 UTC, Cornelius-G commented
> Hm, since those are pretty fundamental, maybe we should offer (some of those) as explicit fields of `OptimAlg` directly, so the user can use them across optimization backends in a consistent fashion?

Hm, I'm not quite sure. It sounds a bit unnecessary to wrap all the options (and would again not give full control to the user).  
I understand that we currently always require `Optim.Options(store_trace = true, extended_trace=true)`, but we could just enforce this by setting these two options explicitly. 

On the other hand, I just had a quick look at Optimization.jl. (I'm not sure, do we have any plans to support this in the future instead of only relying on Optim.jl?) But they seem to actually have a unified interface for common options like the iterations and tolerances: https://docs.sciml.ai/Optimization/stable/API/solve/#CommonSolve.solve-Tuple{OptimizationProblem,%20Any}

2023-09-05 08:45 UTC, oschulz commented
> I understand that we currently always require Optim.Options(store_trace = true, extended_trace=true), but we could just enforce this by setting these two options explicitly.

No, BAT will need control over these, for example for pathfinder (which requires a trace).

In principle, it should be easy for the user to switch between algorithms/backends, so options that most of them will offer we should provide in a generic fashion under common names.

2023-09-05 08:52 UTC, Cornelius-G commented
So I'm also fine to have these options as individual keywords. But feels a bit like reinventing what Optimization.jl is already offering.

2023-09-05 09:33 UTC, oschulz commented
> reinventing what Optimization.jl is already offering

To certain degree, yes. Optimization.jl used to be an extremely heavy dependency, but it's load time has gone down recently. I would still prefer not to tie BAT to a single optimization backend, even if it's a "meta-backend". But we should definitely add support for Optimization.jl as well. It may not be usable in all cases, though, at least in the past it was tricky to make it store gradient traces, which pathfinder will need.

2023-10-06 08:02 UTC, Cornelius-G commented
Hi @oschulz, here is another proposal. 
I now also added a small wrapper for using Optimization.jl with `bat_findmode`. (This wrapper is very basic and there is no deeper handling of the AD as is currently the case for the Optim.jl interface.)
But with this we can now see a bit better how to make the `bat_findmode` interface work for different optimizer packages.
The proposal is now that we have the keywords `maxiters, maxtime, abstol, reltol` as direct keyword arguments for the `OptimAlg`.
(These are the names used by Optimization.jl as the common options for all included optimization algs.) 
In addition there is now the option to pass further `kwargs` which will just be passed to the optimizer and that can contain all the algorithm-specific options. 
For the case of Optim.jl, we currently then just overwrite the (potential) user input for `store_trace = true, extended_trace=true` to ensure that BAT has access to the trace.

Example:
```julia
using BAT

posterior = BAT.example_posterior()

using Optim
alg = OptimAlg(;
    optalg = Optim.NelderMead(parameters=Optim.FixedParameters()),
    maxiters=200,
    kwargs = (f_calls_limit=100,),
)
my_mode = bat_findmode(posterior, alg)

using OptimizationOptimJL
alg = OptimizationAlg(; 
    optalg = OptimizationOptimJL.ParticleSwarm(n_particles=10), 
    maxiters=200, 
    kwargs=(f_calls_limit=50,)
)
my_mode = bat_findmode(posterior, alg)
```
We can discuss the naming of the algorithms and keywords. But I wanted to check first whether this is the right way at all.

2023-10-08 17:56 UTC, oschulz commented
Sorry for the delay - that approach looks good to me!

2024-02-28 13:23 UTC, Cornelius-G commented
Hi @oschulz, I just realized this PR is still open. 
Do you have any more comments on this?

2024-02-28 15:23 UTC, oschulz commented
Let's merge it. :-)

Can you just fix the Docs build failure?

2024-02-29 10:39 UTC, Cornelius-G commented
> Let's merge it. :-)
> 
> Can you just fix the Docs build failure?

Ok, Docs build is fixed. Should be ready to merge then 🙂

2024-05-20 18:32 UTC, oschulz commented
Replaced by #439

2024-06-05 13:50 UTC, oschulz commented
Closing in favor of #442

2024-06-05 13:50 UTC, closed without merging